//
// Created by robert on 12/13/15.
//

#ifndef INTERPRETER_CPP_DIVISIONBYZEROEXCEPTION_HPP
#define INTERPRETER_CPP_DIVISIONBYZEROEXCEPTION_HPP


class DivisionByZeroException {

};


#endif //INTERPRETER_CPP_DIVISIONBYZEROEXCEPTION_HPP
