//
// Created by robert on 12/13/15.
//

#ifndef INTERPRETER_CPP_VARIABLENOTFOUNDEXCEPTION_HPP
#define INTERPRETER_CPP_VARIABLENOTFOUNDEXCEPTION_HPP


class VariableNotFoundException {

};


#endif //INTERPRETER_CPP_VARIABLENOTFOUNDEXCEPTION_HPP
